[book]
authors = ["silverjun-sc <silverjun@supercreative.kr>"]
language = "en"
multilingual = false
src = "src"
title = "Rust Cookbook"

[output.html]
mathjax-support = true

[output.html.playground]
editable = true
line-numbers = true
